# Generated by Django 5.2.16 on 2026-08-21 20:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Web App / SaaS', 'Web App / SaaS'), ('Mobile App', 'Mobile App'), ('Chrome Extension', 'Chrome Extension'), ('Developer Tool / CLI', 'Developer Tool / CLI'), ('Open Source Library', 'Open Source Library'), ('AI / ML Tool', 'AI / ML Tool'), ('Desktop App', 'Desktop App'), ('Portfolio / Website', 'Portfolio / Website')], default='Web App / SaaS', max_length=50)),
                ('current_stage', models.CharField(choices=[('ideation', 'Ideation'), ('planning', 'Planning'), ('architecture', 'Design & Arch'), ('development', 'Development'), ('testing', 'Testing & QA'), ('deployment', 'Deployment'), ('live', 'Live & Shipped')], default='ideation', max_length=20)),
                ('target_deadline', models.DateField()),
                ('start_date', models.DateField()),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('repo_url', models.URLField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='')),
                ('figma_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('pinned', models.BooleanField(default=False)),
                ('tech_research', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('stage', models.CharField(choices=[('ideation', 'Ideation'), ('planning', 'Planning'), ('architecture', 'Design & Arch'), ('development', 'Development'), ('testing', 'Testing & QA'), ('deployment', 'Deployment'), ('live', 'Live & Shipped')], default='planning', max_length=20)),
                ('target_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project')),
            ],
            options={
                'ordering': ['order', 'target_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('problem', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Web App / SaaS', 'Web App / SaaS'), ('Mobile App', 'Mobile App'), ('Chrome Extension', 'Chrome Extension'), ('Developer Tool / CLI', 'Developer Tool / CLI'), ('Open Source Library', 'Open Source Library'), ('AI / ML Tool', 'AI / ML Tool'), ('Desktop App', 'Desktop App'), ('Portfolio / Website', 'Portfolio / Website')], default='Web App / SaaS', max_length=50)),
                ('status', models.CharField(choices=[('spark', 'Spark'), ('evaluating', 'Evaluating'), ('validated', 'Validated'), ('converted', 'Converted'), ('archived', 'Archived')], default='spark', max_length=20)),
                ('sketch_data_url', models.TextField(blank=True, null=True)),
                ('target_audience', models.TextField(blank=True, default='')),
                ('monetization', models.TextField(blank=True, default='')),
                ('mvp_features', models.JSONField(blank=True, default=list)),
                ('feasibility_score', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('market_potential_score', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('excitement_score', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('market_research', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
                ('converted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_ideas', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default='')),
                ('stage', models.CharField(choices=[('ideation', 'Ideation'), ('planning', 'Planning'), ('architecture', 'Design & Arch'), ('development', 'Development'), ('testing', 'Testing & QA'), ('deployment', 'Deployment'), ('live', 'Live & Shipped')], default='development', max_length=20)),
                ('quadrant', models.CharField(choices=[('q1_do', 'Do First'), ('q2_schedule', 'Schedule & Deep Work'), ('q3_delegate', 'Quick Wins / Streamline'), ('q4_eliminate', 'Backlog & Evaluate')], default='q1_do', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.task')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=400)),
                ('task_title', models.CharField(blank=True, default='', max_length=400)),
                ('stage', models.CharField(choices=[('ideation', 'Ideation'), ('planning', 'Planning'), ('architecture', 'Design & Arch'), ('development', 'Development'), ('testing', 'Testing & QA'), ('deployment', 'Deployment'), ('live', 'Live & Shipped')], default='development', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mode', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('stopwatch', 'Stopwatch'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='core.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'current_stage'], name='core_projec_owner_i_ab49ec_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'pinned'], name='core_projec_owner_i_7cda94_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['owner', 'status'], name='core_idea_owner_i_46f2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'completed'], name='core_task_project_beaf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'quadrant'], name='core_task_project_24d455_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['owner', 'timestamp'], name='core_timeen_owner_i_00819c_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['project', 'timestamp'], name='core_timeen_project_7a05a4_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task', 'timestamp'], name='core_timeen_task_id_f7db6f_idx'),
        ),
    ]
