# Generated by Django 5.2.16 on 2026-08-24 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdoc',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdoc',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='linked_docs', to='core.project'),
        ),
    ]
