# Generated by Django 5.2.16 on 2026-08-24 00:38

from django.db import migrations


def backfill(apps, schema_editor):
    ProjectDoc = apps.get_model('core', 'ProjectDoc')
    for doc in ProjectDoc.objects.all().select_related('project'):
        if doc.project_id and doc.owner_id is None:
            doc.owner_id = doc.project.owner_id
            doc.save(update_fields=['owner'])
        if doc.project_id:
            doc.projects.add(doc.project_id)


def unbackfill(apps, schema_editor):
    # Irreversible data copy; nothing meaningful to restore.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectdoc_owner_projectdoc_projects'),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
