# Generated by Django 5.2.16 on 2026-08-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_project_alter_projectdoc_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='directory_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
