# Generated by Django 5.2.16 on 2026-08-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_directory_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('feature', 'Feature'), ('bug', 'Bug'), ('chore', 'Chore'), ('improvement', 'Improvement')], default='feature', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'category'], name='core_task_project_3e6bac_idx'),
        ),
    ]
