# Generated by Django 5.2.16 on 2026-08-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cmd_directory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='script_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
