# Generated by Django 5.2.3 on 2026-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='python_env',
            field=models.CharField(blank=True, default='', help_text='Optional virtualenv folder. Auto-activates in the in-app terminal and is used for script runs (resolves Scripts/activate.bat and Scripts/python.exe).', max_length=500),
        ),
    ]
