# Generated by Django 5.2.3 on 2026-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_python_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drive',
            field=models.CharField(blank=True, choices=[('C', 'C:'), ('D', 'D:'), ('E', 'E:'), ('F', 'F:'), ('G', 'G:'), ('H', 'H:')], default='', help_text="Drive letter for this project's paths (useful when the project lives on a USB drive that gets a different letter on another PC). Changing it remaps cmd_directory/script_path/directory_path.", max_length=2),
        ),
    ]
