# Generated by Django 5.2.16 on 2026-08-27 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectdoc',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='core.agentfilter'),
        ),
        migrations.AddIndex(
            model_name='projectdoc',
            index=models.Index(fields=['owner', 'filter'], name='core_projec_owner_i_9dbf04_idx'),
        ),
    ]
