# Generated by Django 5.2.16 on 2026-09-15 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_editable_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='manual', max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='dailyfocus',
            new_name='core_dailyf_owner_i_c06b8b_idx',
            old_name='core_dailyfo_owner_i_5e5e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_owner_i_787254_idx',
            old_name='core_projec_owner_i_8f2e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='stagechecklistdefault',
            new_name='core_stagec_owner_i_ab8613_idx',
            old_name='core_stagech_owner_i_7bdb03_idx',
        ),
        migrations.RenameIndex(
            model_name='stagereview',
            new_name='core_stager_project_0652dc_idx',
            old_name='core_stagere_project__6cc5db_idx',
        ),
        migrations.RenameIndex(
            model_name='stageworkspace',
            new_name='core_stagew_project_d96182_idx',
            old_name='core_sw_project_stage_idx',
        ),
        migrations.AddField(
            model_name='cloudbackup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cloudbackup',
            index=models.Index(fields=['owner', 'name'], name='core_cloudb_owner_i_8d41ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='cloudbackup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_cloud_backup'),
        ),
    ]
