# Generated by Django 5.2.16 on 2026-09-16 23:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_cloud_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratorRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('awaiting_plan', 'Awaiting plan approval'), ('running', 'Running'), ('paused', 'Paused'), ('needs_approval', 'Needs approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('max_parallel', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestrator_runs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestratorStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('tool', models.CharField(choices=[('opencode', 'OpenCode'), ('codex', 'Codex')], default='opencode', max_length=20)),
                ('model_id', models.CharField(blank=True, default='', max_length=200)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('mode', models.CharField(choices=[('build', 'Build'), ('plan', 'Plan')], default='build', max_length=10)),
                ('skill_ids', models.JSONField(blank=True, default=list)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('awaiting_approval', 'Awaiting approval'), ('sending', 'Sending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('verification_command', models.CharField(blank=True, default='', max_length=500)),
                ('output_tail', models.TextField(blank=True, default='')),
                ('approval_reason', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.orchestratorrun')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestrator_steps', to='core.task')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orchestratorrun',
            index=models.Index(fields=['project', 'status', 'created_at'], name='core_orches_project_95a2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestratorstep',
            index=models.Index(fields=['run', 'status', 'order'], name='core_orches_run_id_ec262e_idx'),
        ),
    ]
