# Generated by Django 5.2.16 on 2026-10-04 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_kilo_initialization_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tool', models.CharField(choices=[('opencode', 'OpenCode'), ('codex', 'Codex'), ('kilo', 'Kilo')], default='opencode', max_length=20)),
                ('model_id', models.CharField(blank=True, default='', max_length=200)),
                ('reasoning_effort', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('mode', models.CharField(choices=[('build', 'Build'), ('plan', 'Plan')], default='build', max_length=10)),
                ('prompt_template', models.TextField()),
                ('schedule_kind', models.CharField(choices=[('daily', 'Daily'), ('every_hours', 'Every X hours'), ('cron', 'Cron expression')], default='daily', max_length=20)),
                ('schedule_value', models.CharField(blank=True, default='09:00', max_length=200)),
                ('timezone_name', models.CharField(blank=True, default='Europe/Athens', max_length=100)),
                ('timeout_minutes', models.PositiveIntegerField(default=15)),
                ('enabled', models.BooleanField(default=True)),
                ('notify_mode', models.CharField(choices=[('always', 'Always'), ('on_alert', 'On alert'), ('on_fail', 'On fail')], default='on_alert', max_length=20)),
                ('windows_task_name', models.CharField(blank=True, default='', max_length=260)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=30)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_id', models.CharField(blank=True, default='', max_length=120)),
                ('coordinator_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='core.project')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CronRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('skipped', 'Skipped'), ('needs_attention', 'Needs attention')], default='queued', max_length=20)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=64)),
                ('output_tail', models.TextField(blank=True, default='')),
                ('structured_result', models.JSONField(blank=True, default=dict)),
                ('notified', models.BooleanField(default=False)),
                ('trigger', models.CharField(blank=True, default='schedule', max_length=30)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.cronjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cronjob',
            index=models.Index(fields=['owner', 'enabled', 'next_run_at'], name='core_cronjo_owner_i_a63cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='cronrun',
            index=models.Index(fields=['job', 'status', 'created_at'], name='core_cronru_job_id_1b93c5_idx'),
        ),
    ]
