# Generated by Django 5.2.16 on 2026-10-04 02:12

from django.db import migrations, models


def carry_project_directory(apps, schema_editor):
    CronJob = apps.get_model('core', 'CronJob')
    Project = apps.get_model('core', 'Project')
    for job in CronJob.objects.all().only('id', 'project', 'working_directory', 'python_env'):
        try:
            project = Project.objects.filter(pk=job.project_id).first()
        except Exception:
            project = None
        if not project:
            continue
        directory = (project.cmd_directory or project.directory_path or '').strip()
        updates = {}
        if directory and not (job.working_directory or '').strip():
            updates['working_directory'] = directory
        if (project.python_env or '').strip() and not (job.python_env or '').strip():
            updates['python_env'] = project.python_env
        if updates:
            CronJob.objects.filter(pk=job.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_cron_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='python_env',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='working_directory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(carry_project_directory, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cronjob',
            name='project',
        ),
    ]
