# Generated by Django 5.2.16 on 2026-10-06 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_user_automation_results_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='stage',
            field=models.CharField(default='planning', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_stage',
            field=models.CharField(default='ideation', max_length=40),
        ),
        migrations.AlterField(
            model_name='stagechecklistdefault',
            name='stage',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stagereview',
            name='stage',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stageworkspace',
            name='stage',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(default='development', max_length=40),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='stage',
            field=models.CharField(default='development', max_length=40),
        ),
        migrations.CreateModel(
            name='StageDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#6366f1', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('builtin_key', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['owner', 'order'], name='core_staged_owner_i_aa8bdb_idx'), models.Index(fields=['owner', 'is_active'], name='core_staged_owner_i_a62c45_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'key'), name='unique_owner_stage_key')],
            },
        ),
    ]
