import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { ChecklistItem, ProjectStage, STAGE_CONFIG } from '../types';
import { ChecklistEditor } from './ChecklistEditor';
import { RotateCcw } from 'lucide-react';

const stages = Object.keys(STAGE_CONFIG) as ProjectStage[];
export const ChecklistDefaultsManager: React.FC = () => {
  const [stage, setStage] = useState<ProjectStage>('ideation');
  const [guided, setGuided] = useState<ChecklistItem[]>([]);
  const [shaping, setShaping] = useState<ChecklistItem[]>([]);
  const [editing, setEditing] = useState<'guided' | 'shaping' | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const load = async () => { setError(null); try { const data = (await api.get(`/settings/checklist-defaults/${stage}/`)).data; setGuided(data.checklist || []); setShaping(data.shaping_checklist || []); } catch { setError('Unable to load checklist defaults.'); } };
  useEffect(() => { void load(); }, [stage]);
  const save = async (group: 'guided' | 'shaping', items: ChecklistItem[]) => { setBusy(true); try { const payload = group === 'guided' ? { checklist: items } : { shaping_checklist: items }; const data = (await api.patch(`/settings/checklist-defaults/${stage}/`, payload)).data; setGuided(data.checklist || []); setShaping(data.shaping_checklist || []); setEditing(null); } catch { setError('Unable to save defaults. Your draft remains in the editor.'); } finally { setBusy(false); } };
  const restore = async () => { if (!window.confirm(`Restore the built-in defaults for ${STAGE_CONFIG[stage].label}?`)) return; setBusy(true); try { const data = (await api.delete(`/settings/checklist-defaults/${stage}/`)).data; setGuided(data.checklist || []); setShaping(data.shaping_checklist || []); } catch { setError('Unable to restore built-in defaults.'); } finally { setBusy(false); } };
  return <div className="space-y-5"><div className="rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-5"><h2 className="text-lg font-black text-content">Checklist defaults</h2><p className="mt-1 max-w-2xl text-sm text-content-muted">Customize the starting checklist for new projects and idea conversions. Existing projects keep their current lists until you apply defaults from their Stage Workspace.</p><label className="mt-4 block text-xs font-bold text-content-muted">Stage<select value={stage} onChange={e => setStage(e.target.value as ProjectStage)} className="ml-2 rounded-lg border border-line bg-surface px-2 py-1.5 text-xs text-content">{stages.map(item => <option key={item} value={item}>{STAGE_CONFIG[item].label}</option>)}</select></label></div>{error && <div className="rounded-xl bg-rose-500/10 border border-rose-500/20 px-4 py-2 text-xs font-bold text-rose-600 dark:text-rose-300" role="alert">{error}</div>}<div className="grid gap-5 lg:grid-cols-2">{editing === 'guided' ? <ChecklistEditor title="Guided checklist" items={guided} saving={busy} onCancel={() => setEditing(null)} onSave={items => save('guided', items)} /> : <ListPreview title="Guided checklist" items={guided} onEdit={() => setEditing('guided')} />}{editing === 'shaping' ? <ChecklistEditor title="Shaping the build" items={shaping} saving={busy} onCancel={() => setEditing(null)} onSave={items => save('shaping', items)} /> : <ListPreview title="Shaping the build" items={shaping} onEdit={() => setEditing('shaping')} />}</div><button type="button" onClick={() => void restore()} disabled={busy} className="inline-flex items-center gap-1.5 rounded-lg border border-line px-3 py-2 text-xs font-bold text-content-faint hover:text-indigo-500 disabled:opacity-50"><RotateCcw className="w-3.5 h-3.5" /> Restore app defaults</button></div>;
};

const ListPreview: React.FC<{ title: string; items: ChecklistItem[]; onEdit: () => void }> = ({ title, items, onEdit }) => <section className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-black text-content">{title}</h3><button type="button" onClick={onEdit} className="rounded-lg border border-line px-2.5 py-1 text-xs font-bold text-content-faint hover:text-indigo-500">Edit checklist</button></div>{items.length ? <ol className="mt-3 space-y-2">{items.map((item, index) => <li key={item.id} className="flex items-center gap-2 rounded-lg bg-surface-2 px-3 py-2 text-xs text-content-muted"><span className="w-5 text-content-faint">{index + 1}.</span>{item.label}</li>)}</ol> : <button type="button" onClick={onEdit} className="mt-3 w-full rounded-xl border border-dashed border-line p-4 text-xs font-bold text-content-faint">Empty list · Add item</button>}</section>;
