import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';
import { LayoutDashboard, FolderKanban, Lightbulb, Grid2X2, Timer, CalendarClock, Plus, Moon, Sun, Play, Pause, Search, Layers, Settings, PanelLeftClose, PanelLeftOpen, MoreHorizontal, X } from 'lucide-react';
import { ActiveView } from '../types';
import { Button, IconButton } from './ui';

export const Navigation: React.FC<{ collapsed: boolean; onToggle: () => void }> = ({ collapsed, onToggle }) => {
  const { isAuthenticated } = useAuth();
  const { currentView, setCurrentView, selectedProjectId, setSelectedProjectId, isDarkMode, toggleDarkMode, searchQuery, setSearchQuery, timeTracker, pauseTimer, resumeTimer, openQuickAdd, projects, tasks, ideas } = useApp();
  const [moreOpen, setMoreOpen] = useState(false);
  const [mobileSearchOpen, setMobileSearchOpen] = useState(false);
  if (!isAuthenticated) return null;
  const formatTimer = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`;
  const navItems: { id: ActiveView; label: string; icon: React.ComponentType<{ className?: string }>; count?: number }[] = [
    { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'projects', label: 'Projects', icon: FolderKanban, count: projects.length },
    { id: 'matrix', label: 'Priority Matrix', icon: Grid2X2, count: tasks.filter(t => !t.completed).length }, { id: 'ideas', label: 'Idea Canvas', icon: Lightbulb, count: ideas.filter(i => i.status !== 'archived').length },
    { id: 'timetracker', label: 'Focus & Timer', icon: Timer }, { id: 'timeline', label: 'Timeline', icon: CalendarClock },
  ];
  const navigate = (view: ActiveView) => {
    if (view === 'projects' && selectedProjectId) setSelectedProjectId(null);
    setCurrentView(view);
    setMoreOpen(false);
  };
  return <>
    <aside className={`fixed inset-y-0 left-0 z-40 hidden flex-col border-r border-line bg-surface/95 dark:bg-surface-inverse/95 backdrop-blur-xl transition-[width] duration-200 md:flex ${collapsed ? 'w-[76px]' : 'w-64'}`}>
      <div className={`flex h-20 items-center border-b border-line px-4 ${collapsed ? 'justify-center' : 'justify-between'}`}>
        <button type="button" onClick={() => navigate('dashboard')} className="flex items-center gap-3 rounded-xl text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-500 text-white shadow-lg shadow-indigo-500/20"><Layers className="h-5 w-5" /></span>{!collapsed && <span><span className="block text-sm font-extrabold tracking-tight text-content">SoloDev Studio</span><span className="mt-0.5 block text-[10px] font-bold uppercase tracking-[0.16em] text-content-muted">Build with intent</span></span>}</button>
        {!collapsed && <IconButton label="Collapse sidebar" onClick={onToggle}><PanelLeftClose className="h-4 w-4" /></IconButton>}
      </div>
      {collapsed && <IconButton label="Expand sidebar" onClick={onToggle} className="mx-auto mt-3"><PanelLeftOpen className="h-4 w-4" /></IconButton>}
      <nav className="flex-1 space-y-1 px-3 py-6" aria-label="Primary navigation"><p className={`mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.18em] text-content-muted ${collapsed ? 'sr-only' : ''}`}>Workspace</p>{navItems.map(({ id, label, icon: Icon, count }) => { const active = currentView === id; return <button key={id} type="button" onClick={() => navigate(id)} title={collapsed ? label : undefined} aria-current={active ? 'page' : undefined} className={`group flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 ${active ? 'bg-indigo-500/15 text-indigo-700 dark:text-indigo-200' : 'text-content-muted hover:bg-surface-2 hover:text-content'} ${collapsed ? 'justify-center' : ''}`}><Icon className={`h-[18px] w-[18px] shrink-0 ${active ? 'text-indigo-700 dark:text-indigo-300' : 'text-content-muted group-hover:text-content'}`} />{!collapsed && <><span className="min-w-0 flex-1 truncate">{label}</span>{count !== undefined && count > 0 && <span className={`rounded-md px-1.5 py-0.5 text-[10px] font-bold ${active ? 'bg-indigo-500/20 text-indigo-700 dark:text-indigo-200' : 'bg-surface-2 text-content-muted'}`}>{count}</span>}</>}</button>; })}</nav>
      <div className={`border-t border-line p-3 ${collapsed ? 'space-y-2' : 'space-y-3'}`}>{timeTracker.isRunning || timeTracker.secondsElapsed > 0 ? <div role="button" tabIndex={0} onClick={() => navigate('timetracker')} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') navigate('timetracker'); }} title={collapsed ? 'Active timer' : undefined} className={`flex w-full items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-2.5 text-left ${collapsed ? 'justify-center' : ''}`}><span className={`h-2 w-2 shrink-0 rounded-full ${timeTracker.isRunning ? 'animate-pulse bg-emerald-400' : 'bg-content-muted'}`} />{!collapsed && <><span className="flex-1 font-mono text-xs font-bold text-emerald-700 dark:text-emerald-200">{formatTimer(timeTracker.mode === 'pomodoro' ? timeTracker.secondsRemaining : timeTracker.secondsElapsed)}</span><button type="button" aria-label={timeTracker.isRunning ? 'Pause timer' : 'Resume timer'} onClick={(e) => { e.stopPropagation(); timeTracker.isRunning ? pauseTimer() : resumeTimer(); }} className="rounded-lg bg-emerald-400 p-1 text-slate-950"><>{timeTracker.isRunning ? <Pause className="h-3 w-3" /> : <Play className="h-3 w-3" />}</></button></>}</div> : null}<div className={`flex items-center gap-2 ${collapsed ? 'flex-col' : ''}`}><IconButton label={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'} onClick={toggleDarkMode}>{isDarkMode ? <Sun className="h-4 w-4 text-amber-700 dark:text-amber-300" /> : <Moon className="h-4 w-4" />}</IconButton><IconButton label="Settings" onClick={() => navigate('settings')} className={currentView === 'settings' ? 'bg-surface-2 text-content' : ''}><Settings className="h-4 w-4" /></IconButton>{!collapsed && <span className="ml-auto text-[10px] font-mono text-content-muted">v1.0</span>}</div></div>
    </aside>
    <header className={`fixed inset-x-0 top-0 z-30 hidden h-16 items-center gap-4 border-b border-line bg-surface/90 dark:bg-surface-inverse/85 px-6 backdrop-blur-xl md:flex ${collapsed ? 'pl-[100px]' : 'pl-[288px]'}`}><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-content">{navItems.find(n => n.id === currentView)?.label || 'Settings'}</p><p className="hidden text-[11px] text-content-muted lg:block">A clear place for your next deliberate move.</p></div><div className="relative hidden w-64 lg:block"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-content-muted" /><input id="global-search-input" value={searchQuery} onChange={e => setSearchQuery(e.target.value)} placeholder="Search workspace" className="w-full rounded-xl border border-line bg-surface-2 py-2 pl-9 pr-3 text-xs text-content outline-none transition focus:border-indigo-400 focus:ring-2 focus:ring-indigo-400/20" /></div><Button size="sm" onClick={() => openQuickAdd('task')}><Plus className="h-4 w-4" />New action</Button></header>
    <header className="fixed inset-x-0 top-0 z-30 flex h-16 items-center justify-between gap-2 border-b border-line bg-surface/90 dark:bg-surface-inverse/90 px-4 backdrop-blur-xl md:hidden"><button type="button" onClick={() => navigate('dashboard')} className="flex shrink-0 items-center gap-2 text-content"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-500 text-white"><Layers className="h-4 w-4" /></span><span className="text-sm font-extrabold">SoloDev Studio</span></button>{mobileSearchOpen && <input autoFocus id="mobile-search-input" value={searchQuery} onChange={e => setSearchQuery(e.target.value)} placeholder="Search" className="min-w-0 flex-1 rounded-lg border border-line bg-surface-2 px-2.5 py-1.5 text-xs text-content outline-none focus:border-indigo-400" />}<div className="flex shrink-0 items-center gap-1"><IconButton label={mobileSearchOpen ? 'Close search' : 'Search workspace'} onClick={() => setMobileSearchOpen(v => !v)}>{mobileSearchOpen ? <X className="h-4 w-4" /> : <Search className="h-4 w-4" />}</IconButton><IconButton label="New action" onClick={() => openQuickAdd('task')}><Plus className="h-4 w-4" /></IconButton></div></header>
    <nav className="fixed inset-x-0 bottom-0 z-40 flex items-center justify-around border-t border-line bg-surface/95 dark:bg-surface-inverse/95 px-2 pb-[env(safe-area-inset-bottom)] pt-2 backdrop-blur-xl md:hidden" aria-label="Mobile navigation">{[navItems[0], navItems[1], navItems[2], navItems[4]].map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => navigate(id)} aria-label={label} className={`flex min-w-16 flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-bold ${currentView === id ? 'text-indigo-700 dark:text-indigo-300' : 'text-content-muted'}`}><Icon className="h-4 w-4" /><span>{id === 'timetracker' ? 'Focus' : label.split(' ')[0]}</span></button>)}<button type="button" onClick={() => setMoreOpen(v => !v)} aria-expanded={moreOpen} className={`flex min-w-16 flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-bold ${moreOpen ? 'text-indigo-700 dark:text-indigo-300' : 'text-content-muted'}`}><MoreHorizontal className="h-4 w-4" /><span>More</span></button></nav>
    {moreOpen && <div className="fixed inset-x-3 bottom-20 z-40 rounded-2xl border border-line bg-surface p-2 shadow-2xl md:hidden"><div className="flex items-center justify-between px-3 py-2"><span className="text-xs font-bold text-content">More workspace</span><IconButton label="Close menu" onClick={() => setMoreOpen(false)}><X className="h-4 w-4" /></IconButton></div>{[navItems[3], navItems[5], { id: 'settings' as ActiveView, label: 'Settings', icon: Settings }].map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => navigate(id)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold text-content-muted hover:bg-surface-2 hover:text-content"><Icon className="h-4 w-4" />{label}</button>)}</div>}
  </>;
};
