const title = document.getElementById('title');
const meta = document.getElementById('meta');
const action = document.getElementById('action');
const pause = document.getElementById('pause');
const root = document.getElementById('root');
let state = null;
const fmt = (seconds) => { const s = Math.max(0, Number(seconds) || 0); return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`; };
const render = () => { const connected = Boolean(state && Date.now() - (state.reportedAt || Date.now()) < 30000); const timer = state?.timer; const task = state?.task; const drift = connected && timer?.active && !timer.paused ? Math.floor((Date.now() - (state.reportedAt || Date.now())) / 1000) : 0; title.textContent = state?.loggedOut ? 'Sign in to continue' : connected && timer?.active ? (timer.taskTitle || 'Focus session') : connected ? (task?.title || 'Choose your next task.') : 'Reconnecting to SoloDev…'; meta.textContent = state?.loggedOut ? 'Companion paused' : connected ? (timer?.active ? `${timer.projectTitle || ''} · ${fmt((timer.secondsRemaining || 0) - drift)} · ${timer.paused ? 'Paused' : 'Running'}` : (task?.projectTitle || 'SoloDev companion')) : 'Main window unavailable'; pause.textContent = timer?.paused ? 'Resume' : 'Pause'; pause.disabled = !connected || !timer?.active || Boolean(state?.loggedOut); action.textContent = timer?.active ? 'Open task' : 'Start focus'; action.disabled = !connected || (!timer?.active && !task) || Boolean(state?.loggedOut); root.classList.toggle('paused', Boolean(timer?.paused || state?.loggedOut)); };
window.soloDevCompanion.onState(next => { state = next; render(); });
document.getElementById('restore').onclick = () => window.soloDevCompanion.command('restore');
document.querySelector('.bubble').onclick = () => window.soloDevCompanion.command('restore-task');
document.getElementById('dismiss').onclick = () => window.soloDevCompanion.dismiss();
pause.onclick = () => window.soloDevCompanion.command(state?.timer?.paused ? 'resume' : 'pause');
action.onclick = () => window.soloDevCompanion.command(state?.timer?.active ? 'restore-task' : 'start-focus');
let dragging = false; let moved = false; let origin = null;
document.getElementById('robot').addEventListener('pointerdown', event => { dragging = true; moved = false; origin = { x: event.screenX, y: event.screenY }; event.currentTarget.setPointerCapture(event.pointerId); });
document.getElementById('robot').addEventListener('pointermove', event => { if (!dragging || !origin) return; moved = moved || Math.abs(event.screenX - origin.x) > 4 || Math.abs(event.screenY - origin.y) > 4; window.soloDevCompanion.move({ x: event.screenX - 126, y: event.screenY - 164 }); });
document.getElementById('robot').addEventListener('pointerup', () => { if (dragging && !moved) window.soloDevCompanion.command('restore'); dragging = false; origin = null; });
render();
setInterval(render, 1000);
